resolver: lts-5.12
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

packages:
- '.'

extra-deps:
- ghcjs-dom-0.2.3.1
- reflex-dom-0.3
- reflex-0.4.0
- ref-tf-0.4
- haskell-src-exts-1.16.0.1
- reflex-dom-contrib-0.4.1
- tidal-0.8.2
- hosc-0.15
- hmt-0.15
- multiset-comb-0.2.4.1
- permutation-0.5.0.5

