resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- '.'
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: d5e5518d228ae895f6a83b17dc0ae794d4b9eec5
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: c17d6c3cd30707d14d700c8874bdd825be6f65c6
  extra-dep: true
- location:
    git: https://github.com/tidalcycles/Tidal.git
    commit: b3e44108a6986be63475e9128993dac4f9c5fdd0
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- ref-tf-0.4
- ghcjs-dom-0.2.3.1
- these-0.6.1.0
- hmt-0.15
- hosc-0.15
- multiset-comb-0.2.4
- permutation-0.5.0.5
- reflex-0.4.0
- reflex-dom-0.3.2
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
