resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 644b1a056f6689bdf6c0eed83cce576889a14284
  subdirs:
  - reflex-dom-core
  - reflex-dom
  extra-dep: true

extra-deps:
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsffi-0.8.0.0
- text-1.2.2.1
- ref-tf-0.4
- haskell-src-exts-1.16.0.1
- reflex-dom-contrib-0.4.1
- tidal-0.8.2
- hosc-0.15
- hmt-0.15
- multiset-comb-0.2.4.1
- permutation-0.5.0.5
- prim-uniq-0.1.0.1
- zenc-0.1.1
- dependent-map-0.2.4.0
- keycode-0.2.2
- jsaddle-0.8.0.1
- dependent-sum-template-0.0.0.5


